[workspace]
resolver = "2"
members = ["crates/rtb-ffi", "crates/rtb-core", "crates/rtb-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Manish Kumar Jha <manishyoudumb@gmail.com>"]
